"""Built-in database of 100+ common drugs with pharmacological properties.

Each entry includes generic name, brand names, drug class, mechanism of action,
CYP450 enzyme interactions, half-life, protein binding, and therapeutic-index
flags.  This is a curated reference dataset -- not a substitute for a live
formulary.
"""

from __future__ import annotations

from typing import Optional

from aushadhi.models import CYP450Entry, CYP450Role, Drug, DrugClass


# ---------------------------------------------------------------------------
# Raw drug records -- kept as dicts for readability, converted to Drug models
# on first access via DrugDatabase.
# ---------------------------------------------------------------------------

_RAW_DRUGS: list[dict] = [
    # ---- Cardiovascular ----
    {
        "name": "warfarin",
        "brand_names": ["Coumadin"],
        "drug_class": DrugClass.ANTICOAGULANT,
        "mechanism": "Inhibits vitamin K epoxide reductase (VKORC1), blocking synthesis of clotting factors II, VII, IX, X",
        "cyp450": [("CYP2C9", "substrate"), ("CYP3A4", "substrate"), ("CYP1A2", "substrate")],
        "half_life_hours": 40.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "heparin",
        "brand_names": ["Heparin"],
        "drug_class": DrugClass.ANTICOAGULANT,
        "mechanism": "Potentiates antithrombin III, inactivating thrombin and factor Xa",
        "cyp450": [],
        "half_life_hours": 1.5,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "apixaban",
        "brand_names": ["Eliquis"],
        "drug_class": DrugClass.ANTICOAGULANT,
        "mechanism": "Direct factor Xa inhibitor",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 12.0,
        "protein_binding_pct": 87.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "rivaroxaban",
        "brand_names": ["Xarelto"],
        "drug_class": DrugClass.ANTICOAGULANT,
        "mechanism": "Direct factor Xa inhibitor",
        "cyp450": [("CYP3A4", "substrate"), ("CYP2C8", "substrate")],
        "half_life_hours": 9.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "aspirin",
        "brand_names": ["Bayer", "Ecotrin"],
        "drug_class": DrugClass.ANTIPLATELET,
        "mechanism": "Irreversible COX-1 inhibition preventing thromboxane A2 synthesis",
        "cyp450": [],
        "half_life_hours": 0.25,
        "protein_binding_pct": 80.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "clopidogrel",
        "brand_names": ["Plavix"],
        "drug_class": DrugClass.ANTIPLATELET,
        "mechanism": "Irreversible P2Y12 ADP receptor antagonist on platelets",
        "cyp450": [("CYP2C19", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 6.0,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "ticagrelor",
        "brand_names": ["Brilinta"],
        "drug_class": DrugClass.ANTIPLATELET,
        "mechanism": "Reversible P2Y12 ADP receptor antagonist",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 7.0,
        "protein_binding_pct": 99.7,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "lisinopril",
        "brand_names": ["Prinivil", "Zestril"],
        "drug_class": DrugClass.ACE_INHIBITOR,
        "mechanism": "Inhibits angiotensin-converting enzyme, reducing angiotensin II",
        "cyp450": [],
        "half_life_hours": 12.0,
        "protein_binding_pct": 25.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "enalapril",
        "brand_names": ["Vasotec"],
        "drug_class": DrugClass.ACE_INHIBITOR,
        "mechanism": "ACE inhibitor prodrug; active metabolite enalaprilat blocks ACE",
        "cyp450": [],
        "half_life_hours": 11.0,
        "protein_binding_pct": 50.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "ramipril",
        "brand_names": ["Altace"],
        "drug_class": DrugClass.ACE_INHIBITOR,
        "mechanism": "ACE inhibitor prodrug; active metabolite ramiprilat blocks ACE",
        "cyp450": [],
        "half_life_hours": 13.0,
        "protein_binding_pct": 73.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "losartan",
        "brand_names": ["Cozaar"],
        "drug_class": DrugClass.ARB,
        "mechanism": "Selective AT1 angiotensin II receptor antagonist",
        "cyp450": [("CYP2C9", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 6.0,
        "protein_binding_pct": 98.7,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "valsartan",
        "brand_names": ["Diovan"],
        "drug_class": DrugClass.ARB,
        "mechanism": "Selective AT1 angiotensin II receptor antagonist",
        "cyp450": [],
        "half_life_hours": 6.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "irbesartan",
        "brand_names": ["Avapro"],
        "drug_class": DrugClass.ARB,
        "mechanism": "Selective AT1 angiotensin II receptor antagonist",
        "cyp450": [("CYP2C9", "substrate")],
        "half_life_hours": 15.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "metoprolol",
        "brand_names": ["Lopressor", "Toprol-XL"],
        "drug_class": DrugClass.BETA_BLOCKER,
        "mechanism": "Selective beta-1 adrenergic receptor antagonist",
        "cyp450": [("CYP2D6", "substrate")],
        "half_life_hours": 5.0,
        "protein_binding_pct": 12.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "atenolol",
        "brand_names": ["Tenormin"],
        "drug_class": DrugClass.BETA_BLOCKER,
        "mechanism": "Selective beta-1 adrenergic receptor antagonist",
        "cyp450": [],
        "half_life_hours": 7.0,
        "protein_binding_pct": 6.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "propranolol",
        "brand_names": ["Inderal"],
        "drug_class": DrugClass.BETA_BLOCKER,
        "mechanism": "Non-selective beta adrenergic receptor antagonist",
        "cyp450": [("CYP2D6", "substrate"), ("CYP1A2", "substrate"), ("CYP2C19", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "carvedilol",
        "brand_names": ["Coreg"],
        "drug_class": DrugClass.BETA_BLOCKER,
        "mechanism": "Non-selective beta and alpha-1 adrenergic receptor antagonist",
        "cyp450": [("CYP2D6", "substrate"), ("CYP2C9", "substrate")],
        "half_life_hours": 7.0,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "amlodipine",
        "brand_names": ["Norvasc"],
        "drug_class": DrugClass.CCB,
        "mechanism": "Dihydropyridine L-type calcium channel blocker; arterial vasodilator",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 40.0,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "diltiazem",
        "brand_names": ["Cardizem", "Tiazac"],
        "drug_class": DrugClass.CCB,
        "mechanism": "Benzothiazepine calcium channel blocker; slows AV conduction",
        "cyp450": [("CYP3A4", "substrate"), ("CYP3A4", "inhibitor")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 80.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "verapamil",
        "brand_names": ["Calan", "Verelan"],
        "drug_class": DrugClass.CCB,
        "mechanism": "Phenylalkylamine calcium channel blocker; negative chronotrope/inotrope",
        "cyp450": [("CYP3A4", "substrate"), ("CYP3A4", "inhibitor"), ("CYP1A2", "inhibitor")],
        "half_life_hours": 7.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "nifedipine",
        "brand_names": ["Procardia", "Adalat"],
        "drug_class": DrugClass.CCB,
        "mechanism": "Dihydropyridine calcium channel blocker; potent arterial vasodilator",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 2.0,
        "protein_binding_pct": 96.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "hydrochlorothiazide",
        "brand_names": ["Microzide"],
        "drug_class": DrugClass.DIURETIC,
        "mechanism": "Thiazide diuretic inhibiting Na/Cl co-transporter in distal tubule",
        "cyp450": [],
        "half_life_hours": 10.0,
        "protein_binding_pct": 68.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "furosemide",
        "brand_names": ["Lasix"],
        "drug_class": DrugClass.DIURETIC,
        "mechanism": "Loop diuretic inhibiting Na/K/2Cl co-transporter in thick ascending limb",
        "cyp450": [],
        "half_life_hours": 1.5,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "spironolactone",
        "brand_names": ["Aldactone"],
        "drug_class": DrugClass.DIURETIC,
        "mechanism": "Aldosterone receptor antagonist (potassium-sparing diuretic)",
        "cyp450": [],
        "half_life_hours": 1.4,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "amiodarone",
        "brand_names": ["Cordarone", "Pacerone"],
        "drug_class": DrugClass.ANTIARRHYTHMIC,
        "mechanism": "Class III antiarrhythmic; blocks K+, Na+, Ca2+ channels and beta receptors",
        "cyp450": [
            ("CYP3A4", "inhibitor"),
            ("CYP2C9", "inhibitor"),
            ("CYP2D6", "inhibitor"),
            ("CYP3A4", "substrate"),
        ],
        "half_life_hours": 800.0,
        "protein_binding_pct": 96.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "digoxin",
        "brand_names": ["Lanoxin"],
        "drug_class": DrugClass.ANTIARRHYTHMIC,
        "mechanism": "Cardiac glycoside; inhibits Na/K ATPase increasing intracellular Ca2+",
        "cyp450": [],
        "half_life_hours": 39.0,
        "protein_binding_pct": 25.0,
        "narrow_therapeutic_index": True,
    },
    # ---- Statins ----
    {
        "name": "atorvastatin",
        "brand_names": ["Lipitor"],
        "drug_class": DrugClass.STATIN,
        "mechanism": "HMG-CoA reductase inhibitor reducing hepatic cholesterol synthesis",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 14.0,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "simvastatin",
        "brand_names": ["Zocor"],
        "drug_class": DrugClass.STATIN,
        "mechanism": "HMG-CoA reductase inhibitor (prodrug lactone form)",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 3.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "rosuvastatin",
        "brand_names": ["Crestor"],
        "drug_class": DrugClass.STATIN,
        "mechanism": "HMG-CoA reductase inhibitor with high hepatic selectivity",
        "cyp450": [("CYP2C9", "substrate")],
        "half_life_hours": 19.0,
        "protein_binding_pct": 88.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "pravastatin",
        "brand_names": ["Pravachol"],
        "drug_class": DrugClass.STATIN,
        "mechanism": "Hydrophilic HMG-CoA reductase inhibitor; minimal CYP metabolism",
        "cyp450": [],
        "half_life_hours": 2.0,
        "protein_binding_pct": 50.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "lovastatin",
        "brand_names": ["Mevacor"],
        "drug_class": DrugClass.STATIN,
        "mechanism": "HMG-CoA reductase inhibitor (prodrug lactone form)",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 2.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Diabetes ----
    {
        "name": "metformin",
        "brand_names": ["Glucophage"],
        "drug_class": DrugClass.ANTIDIABETIC,
        "mechanism": "Biguanide; activates AMPK, reduces hepatic glucose output",
        "cyp450": [],
        "half_life_hours": 5.0,
        "protein_binding_pct": 0.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "glipizide",
        "brand_names": ["Glucotrol"],
        "drug_class": DrugClass.ANTIDIABETIC,
        "mechanism": "Sulfonylurea; stimulates pancreatic beta-cell insulin secretion",
        "cyp450": [("CYP2C9", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "glyburide",
        "brand_names": ["DiaBeta", "Micronase"],
        "drug_class": DrugClass.ANTIDIABETIC,
        "mechanism": "Sulfonylurea; stimulates pancreatic beta-cell insulin secretion",
        "cyp450": [("CYP2C9", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 5.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "pioglitazone",
        "brand_names": ["Actos"],
        "drug_class": DrugClass.ANTIDIABETIC,
        "mechanism": "Thiazolidinedione; PPAR-gamma agonist improving insulin sensitivity",
        "cyp450": [("CYP2C8", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 7.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "sitagliptin",
        "brand_names": ["Januvia"],
        "drug_class": DrugClass.ANTIDIABETIC,
        "mechanism": "DPP-4 inhibitor; increases incretin levels to enhance insulin secretion",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 12.0,
        "protein_binding_pct": 38.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "empagliflozin",
        "brand_names": ["Jardiance"],
        "drug_class": DrugClass.ANTIDIABETIC,
        "mechanism": "SGLT2 inhibitor; blocks renal glucose reabsorption",
        "cyp450": [],
        "half_life_hours": 12.4,
        "protein_binding_pct": 86.0,
        "narrow_therapeutic_index": False,
    },
    # ---- GI ----
    {
        "name": "omeprazole",
        "brand_names": ["Prilosec"],
        "drug_class": DrugClass.PPI,
        "mechanism": "Irreversible proton pump (H+/K+ ATPase) inhibitor",
        "cyp450": [("CYP2C19", "substrate"), ("CYP2C19", "inhibitor"), ("CYP3A4", "substrate")],
        "half_life_hours": 1.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "esomeprazole",
        "brand_names": ["Nexium"],
        "drug_class": DrugClass.PPI,
        "mechanism": "S-isomer of omeprazole; irreversible proton pump inhibitor",
        "cyp450": [("CYP2C19", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 1.5,
        "protein_binding_pct": 97.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "pantoprazole",
        "brand_names": ["Protonix"],
        "drug_class": DrugClass.PPI,
        "mechanism": "Irreversible proton pump inhibitor with lower CYP interaction profile",
        "cyp450": [("CYP2C19", "substrate")],
        "half_life_hours": 1.0,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "lansoprazole",
        "brand_names": ["Prevacid"],
        "drug_class": DrugClass.PPI,
        "mechanism": "Irreversible proton pump inhibitor",
        "cyp450": [("CYP2C19", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 1.5,
        "protein_binding_pct": 97.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "ranitidine",
        "brand_names": ["Zantac"],
        "drug_class": DrugClass.H2_BLOCKER,
        "mechanism": "Competitive histamine H2 receptor antagonist on parietal cells",
        "cyp450": [],
        "half_life_hours": 2.5,
        "protein_binding_pct": 15.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "famotidine",
        "brand_names": ["Pepcid"],
        "drug_class": DrugClass.H2_BLOCKER,
        "mechanism": "Competitive histamine H2 receptor antagonist",
        "cyp450": [],
        "half_life_hours": 3.0,
        "protein_binding_pct": 17.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "ondansetron",
        "brand_names": ["Zofran"],
        "drug_class": DrugClass.ANTIEMETIC,
        "mechanism": "Selective 5-HT3 receptor antagonist in CTZ and vagal afferents",
        "cyp450": [("CYP3A4", "substrate"), ("CYP1A2", "substrate"), ("CYP2D6", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 73.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "metoclopramide",
        "brand_names": ["Reglan"],
        "drug_class": DrugClass.ANTIEMETIC,
        "mechanism": "Dopamine D2 receptor antagonist and 5-HT4 agonist; prokinetic",
        "cyp450": [("CYP2D6", "substrate")],
        "half_life_hours": 5.0,
        "protein_binding_pct": 30.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Analgesics / NSAIDs / Opioids ----
    {
        "name": "acetaminophen",
        "brand_names": ["Tylenol"],
        "drug_class": DrugClass.ANALGESIC,
        "mechanism": "Central COX inhibition and activation of descending serotonergic pathways",
        "cyp450": [("CYP2E1", "substrate"), ("CYP1A2", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 2.5,
        "protein_binding_pct": 25.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "ibuprofen",
        "brand_names": ["Advil", "Motrin"],
        "drug_class": DrugClass.NSAID,
        "mechanism": "Non-selective COX-1/COX-2 inhibitor",
        "cyp450": [("CYP2C9", "substrate")],
        "half_life_hours": 2.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "naproxen",
        "brand_names": ["Aleve", "Naprosyn"],
        "drug_class": DrugClass.NSAID,
        "mechanism": "Non-selective COX-1/COX-2 inhibitor",
        "cyp450": [("CYP2C9", "substrate")],
        "half_life_hours": 14.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "diclofenac",
        "brand_names": ["Voltaren"],
        "drug_class": DrugClass.NSAID,
        "mechanism": "Non-selective COX inhibitor with some COX-2 preference",
        "cyp450": [("CYP2C9", "substrate")],
        "half_life_hours": 2.0,
        "protein_binding_pct": 99.7,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "celecoxib",
        "brand_names": ["Celebrex"],
        "drug_class": DrugClass.NSAID,
        "mechanism": "Selective COX-2 inhibitor",
        "cyp450": [("CYP2C9", "substrate")],
        "half_life_hours": 11.0,
        "protein_binding_pct": 97.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "meloxicam",
        "brand_names": ["Mobic"],
        "drug_class": DrugClass.NSAID,
        "mechanism": "Preferential COX-2 inhibitor",
        "cyp450": [("CYP2C9", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 20.0,
        "protein_binding_pct": 99.4,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "morphine",
        "brand_names": ["MS Contin"],
        "drug_class": DrugClass.OPIOID,
        "mechanism": "Mu-opioid receptor agonist in CNS",
        "cyp450": [],
        "half_life_hours": 3.0,
        "protein_binding_pct": 35.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "oxycodone",
        "brand_names": ["OxyContin", "Percocet"],
        "drug_class": DrugClass.OPIOID,
        "mechanism": "Semisynthetic mu-opioid receptor agonist",
        "cyp450": [("CYP3A4", "substrate"), ("CYP2D6", "substrate")],
        "half_life_hours": 4.5,
        "protein_binding_pct": 45.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "hydrocodone",
        "brand_names": ["Vicodin", "Norco"],
        "drug_class": DrugClass.OPIOID,
        "mechanism": "Semisynthetic mu-opioid receptor agonist",
        "cyp450": [("CYP2D6", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 36.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "codeine",
        "brand_names": ["Tylenol with Codeine"],
        "drug_class": DrugClass.OPIOID,
        "mechanism": "Prodrug metabolized by CYP2D6 to morphine; mu-opioid agonist",
        "cyp450": [("CYP2D6", "substrate")],
        "half_life_hours": 3.0,
        "protein_binding_pct": 7.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "fentanyl",
        "brand_names": ["Duragesic", "Sublimaze"],
        "drug_class": DrugClass.OPIOID,
        "mechanism": "Potent synthetic mu-opioid receptor agonist",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 80.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "tramadol",
        "brand_names": ["Ultram"],
        "drug_class": DrugClass.OPIOID,
        "mechanism": "Weak mu-opioid agonist and serotonin/norepinephrine reuptake inhibitor",
        "cyp450": [("CYP2D6", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 6.0,
        "protein_binding_pct": 20.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "methadone",
        "brand_names": ["Dolophine"],
        "drug_class": DrugClass.OPIOID,
        "mechanism": "Mu-opioid agonist and NMDA receptor antagonist",
        "cyp450": [("CYP3A4", "substrate"), ("CYP2B6", "substrate"), ("CYP2D6", "substrate")],
        "half_life_hours": 30.0,
        "protein_binding_pct": 85.0,
        "narrow_therapeutic_index": True,
    },
    # ---- Antidepressants ----
    {
        "name": "fluoxetine",
        "brand_names": ["Prozac"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Selective serotonin reuptake inhibitor (SSRI)",
        "cyp450": [("CYP2D6", "inhibitor"), ("CYP2C9", "inhibitor"), ("CYP2D6", "substrate")],
        "half_life_hours": 48.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "sertraline",
        "brand_names": ["Zoloft"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Selective serotonin reuptake inhibitor (SSRI)",
        "cyp450": [("CYP2B6", "substrate"), ("CYP2C19", "substrate"), ("CYP2D6", "inhibitor")],
        "half_life_hours": 26.0,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "paroxetine",
        "brand_names": ["Paxil"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Selective serotonin reuptake inhibitor (SSRI)",
        "cyp450": [("CYP2D6", "substrate"), ("CYP2D6", "inhibitor")],
        "half_life_hours": 21.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "citalopram",
        "brand_names": ["Celexa"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Selective serotonin reuptake inhibitor (SSRI)",
        "cyp450": [("CYP2C19", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 35.0,
        "protein_binding_pct": 80.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "escitalopram",
        "brand_names": ["Lexapro"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "S-enantiomer SSRI with high serotonin transporter selectivity",
        "cyp450": [("CYP2C19", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 30.0,
        "protein_binding_pct": 56.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "venlafaxine",
        "brand_names": ["Effexor"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Serotonin-norepinephrine reuptake inhibitor (SNRI)",
        "cyp450": [("CYP2D6", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 5.0,
        "protein_binding_pct": 27.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "duloxetine",
        "brand_names": ["Cymbalta"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Serotonin-norepinephrine reuptake inhibitor (SNRI)",
        "cyp450": [("CYP1A2", "substrate"), ("CYP2D6", "substrate"), ("CYP2D6", "inhibitor")],
        "half_life_hours": 12.0,
        "protein_binding_pct": 96.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "bupropion",
        "brand_names": ["Wellbutrin", "Zyban"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Norepinephrine-dopamine reuptake inhibitor (NDRI)",
        "cyp450": [("CYP2B6", "substrate"), ("CYP2D6", "inhibitor")],
        "half_life_hours": 21.0,
        "protein_binding_pct": 84.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "amitriptyline",
        "brand_names": ["Elavil"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Tricyclic antidepressant; inhibits serotonin and norepinephrine reuptake",
        "cyp450": [("CYP2D6", "substrate"), ("CYP2C19", "substrate"), ("CYP1A2", "substrate")],
        "half_life_hours": 20.0,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "nortriptyline",
        "brand_names": ["Pamelor"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Tricyclic antidepressant; preferential norepinephrine reuptake inhibitor",
        "cyp450": [("CYP2D6", "substrate")],
        "half_life_hours": 28.0,
        "protein_binding_pct": 93.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "trazodone",
        "brand_names": ["Desyrel"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Serotonin antagonist and reuptake inhibitor (SARI)",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 7.0,
        "protein_binding_pct": 92.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "mirtazapine",
        "brand_names": ["Remeron"],
        "drug_class": DrugClass.ANTIDEPRESSANT,
        "mechanism": "Noradrenergic and specific serotonergic antidepressant (NaSSA); alpha-2 antagonist",
        "cyp450": [("CYP1A2", "substrate"), ("CYP2D6", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 30.0,
        "protein_binding_pct": 85.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Antipsychotics ----
    {
        "name": "quetiapine",
        "brand_names": ["Seroquel"],
        "drug_class": DrugClass.ANTIPSYCHOTIC,
        "mechanism": "Atypical antipsychotic; D2 and 5-HT2A receptor antagonist",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 7.0,
        "protein_binding_pct": 83.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "olanzapine",
        "brand_names": ["Zyprexa"],
        "drug_class": DrugClass.ANTIPSYCHOTIC,
        "mechanism": "Atypical antipsychotic; multi-receptor antagonist (D2, 5-HT2, muscarinic)",
        "cyp450": [("CYP1A2", "substrate"), ("CYP2D6", "substrate")],
        "half_life_hours": 30.0,
        "protein_binding_pct": 93.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "risperidone",
        "brand_names": ["Risperdal"],
        "drug_class": DrugClass.ANTIPSYCHOTIC,
        "mechanism": "Atypical antipsychotic; D2 and 5-HT2A receptor antagonist",
        "cyp450": [("CYP2D6", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 6.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "aripiprazole",
        "brand_names": ["Abilify"],
        "drug_class": DrugClass.ANTIPSYCHOTIC,
        "mechanism": "Atypical antipsychotic; partial D2 agonist and 5-HT2A antagonist",
        "cyp450": [("CYP2D6", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 75.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "haloperidol",
        "brand_names": ["Haldol"],
        "drug_class": DrugClass.ANTIPSYCHOTIC,
        "mechanism": "Typical antipsychotic; potent D2 receptor antagonist",
        "cyp450": [("CYP3A4", "substrate"), ("CYP2D6", "substrate")],
        "half_life_hours": 18.0,
        "protein_binding_pct": 92.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Anxiolytics / Sedatives ----
    {
        "name": "alprazolam",
        "brand_names": ["Xanax"],
        "drug_class": DrugClass.ANXIOLYTIC,
        "mechanism": "Benzodiazepine; GABA-A receptor positive allosteric modulator",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 11.0,
        "protein_binding_pct": 80.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "lorazepam",
        "brand_names": ["Ativan"],
        "drug_class": DrugClass.ANXIOLYTIC,
        "mechanism": "Benzodiazepine; GABA-A receptor positive allosteric modulator",
        "cyp450": [],
        "half_life_hours": 12.0,
        "protein_binding_pct": 85.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "diazepam",
        "brand_names": ["Valium"],
        "drug_class": DrugClass.ANXIOLYTIC,
        "mechanism": "Benzodiazepine; GABA-A receptor positive allosteric modulator",
        "cyp450": [("CYP2C19", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 40.0,
        "protein_binding_pct": 98.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "clonazepam",
        "brand_names": ["Klonopin"],
        "drug_class": DrugClass.ANXIOLYTIC,
        "mechanism": "Benzodiazepine; GABA-A receptor positive allosteric modulator",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 35.0,
        "protein_binding_pct": 85.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "zolpidem",
        "brand_names": ["Ambien"],
        "drug_class": DrugClass.SEDATIVE,
        "mechanism": "Non-benzodiazepine (Z-drug); selective GABA-A alpha-1 subunit agonist",
        "cyp450": [("CYP3A4", "substrate"), ("CYP1A2", "substrate")],
        "half_life_hours": 2.5,
        "protein_binding_pct": 92.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "buspirone",
        "brand_names": ["Buspar"],
        "drug_class": DrugClass.ANXIOLYTIC,
        "mechanism": "5-HT1A partial agonist; non-benzodiazepine anxiolytic",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 2.5,
        "protein_binding_pct": 95.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Anticonvulsants ----
    {
        "name": "phenytoin",
        "brand_names": ["Dilantin"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Sodium channel blocker stabilizing neuronal membranes",
        "cyp450": [
            ("CYP2C9", "substrate"),
            ("CYP2C19", "substrate"),
            ("CYP3A4", "inducer"),
            ("CYP2C9", "inducer"),
        ],
        "half_life_hours": 22.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "carbamazepine",
        "brand_names": ["Tegretol"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Sodium channel blocker; also inhibits glutamate release",
        "cyp450": [
            ("CYP3A4", "substrate"),
            ("CYP3A4", "inducer"),
            ("CYP2C9", "inducer"),
            ("CYP1A2", "inducer"),
        ],
        "half_life_hours": 16.0,
        "protein_binding_pct": 76.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "valproic acid",
        "brand_names": ["Depakote", "Depakene"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Multiple mechanisms: GABA enhancement, sodium channel block, T-type Ca2+ block",
        "cyp450": [
            ("CYP2C9", "substrate"),
            ("CYP2C9", "inhibitor"),
            ("CYP2C19", "inhibitor"),
            ("CYP3A4", "inhibitor"),
        ],
        "half_life_hours": 13.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "lamotrigine",
        "brand_names": ["Lamictal"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Sodium channel blocker; also inhibits glutamate release",
        "cyp450": [],
        "half_life_hours": 25.0,
        "protein_binding_pct": 55.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "levetiracetam",
        "brand_names": ["Keppra"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Binds synaptic vesicle protein SV2A modulating neurotransmitter release",
        "cyp450": [],
        "half_life_hours": 7.0,
        "protein_binding_pct": 10.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "gabapentin",
        "brand_names": ["Neurontin"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Binds alpha-2-delta subunit of voltage-gated calcium channels",
        "cyp450": [],
        "half_life_hours": 6.0,
        "protein_binding_pct": 3.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "pregabalin",
        "brand_names": ["Lyrica"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Binds alpha-2-delta subunit of voltage-gated calcium channels",
        "cyp450": [],
        "half_life_hours": 6.3,
        "protein_binding_pct": 0.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "topiramate",
        "brand_names": ["Topamax"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Multiple mechanisms: Na+ channel block, GABA enhancement, glutamate inhibition",
        "cyp450": [("CYP3A4", "inducer")],
        "half_life_hours": 21.0,
        "protein_binding_pct": 15.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "phenobarbital",
        "brand_names": ["Luminal"],
        "drug_class": DrugClass.ANTICONVULSANT,
        "mechanism": "Barbiturate; enhances GABA-A receptor activity and blocks glutamate",
        "cyp450": [
            ("CYP2C9", "inducer"),
            ("CYP2C19", "inducer"),
            ("CYP3A4", "inducer"),
        ],
        "half_life_hours": 80.0,
        "protein_binding_pct": 45.0,
        "narrow_therapeutic_index": True,
    },
    # ---- Antibiotics ----
    {
        "name": "amoxicillin",
        "brand_names": ["Amoxil"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Beta-lactam; inhibits bacterial cell wall transpeptidase (PBP)",
        "cyp450": [],
        "half_life_hours": 1.0,
        "protein_binding_pct": 20.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "azithromycin",
        "brand_names": ["Zithromax"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Macrolide; binds 50S ribosomal subunit inhibiting bacterial protein synthesis",
        "cyp450": [],
        "half_life_hours": 68.0,
        "protein_binding_pct": 50.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "clarithromycin",
        "brand_names": ["Biaxin"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Macrolide; binds 50S ribosomal subunit inhibiting protein synthesis",
        "cyp450": [("CYP3A4", "inhibitor"), ("CYP3A4", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 70.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "erythromycin",
        "brand_names": ["Erythrocin"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Macrolide; binds 50S ribosomal subunit inhibiting protein synthesis",
        "cyp450": [("CYP3A4", "inhibitor"), ("CYP3A4", "substrate")],
        "half_life_hours": 1.5,
        "protein_binding_pct": 80.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "ciprofloxacin",
        "brand_names": ["Cipro"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Fluoroquinolone; inhibits bacterial DNA gyrase and topoisomerase IV",
        "cyp450": [("CYP1A2", "inhibitor")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 30.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "levofloxacin",
        "brand_names": ["Levaquin"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Fluoroquinolone; inhibits bacterial DNA gyrase and topoisomerase IV",
        "cyp450": [],
        "half_life_hours": 7.0,
        "protein_binding_pct": 30.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "metronidazole",
        "brand_names": ["Flagyl"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Nitroimidazole; forms cytotoxic intermediates damaging bacterial DNA",
        "cyp450": [("CYP2C9", "inhibitor")],
        "half_life_hours": 8.0,
        "protein_binding_pct": 20.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "doxycycline",
        "brand_names": ["Vibramycin"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Tetracycline; binds 30S ribosomal subunit inhibiting protein synthesis",
        "cyp450": [],
        "half_life_hours": 18.0,
        "protein_binding_pct": 93.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "trimethoprim-sulfamethoxazole",
        "brand_names": ["Bactrim", "Septra"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Sequential blockade of folate synthesis (DHPS and DHFR inhibition)",
        "cyp450": [("CYP2C9", "inhibitor")],
        "half_life_hours": 10.0,
        "protein_binding_pct": 70.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "clindamycin",
        "brand_names": ["Cleocin"],
        "drug_class": DrugClass.ANTIBIOTIC,
        "mechanism": "Lincosamide; binds 50S ribosomal subunit inhibiting protein synthesis",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 3.0,
        "protein_binding_pct": 94.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Antifungals ----
    {
        "name": "fluconazole",
        "brand_names": ["Diflucan"],
        "drug_class": DrugClass.ANTIFUNGAL,
        "mechanism": "Triazole; inhibits fungal CYP51 (lanosterol 14-alpha-demethylase)",
        "cyp450": [("CYP2C9", "inhibitor"), ("CYP2C19", "inhibitor"), ("CYP3A4", "inhibitor")],
        "half_life_hours": 30.0,
        "protein_binding_pct": 12.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "ketoconazole",
        "brand_names": ["Nizoral"],
        "drug_class": DrugClass.ANTIFUNGAL,
        "mechanism": "Imidazole; potent inhibitor of fungal and human CYP enzymes",
        "cyp450": [("CYP3A4", "inhibitor")],
        "half_life_hours": 8.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "itraconazole",
        "brand_names": ["Sporanox"],
        "drug_class": DrugClass.ANTIFUNGAL,
        "mechanism": "Triazole; inhibits fungal CYP51 ergosterol synthesis",
        "cyp450": [("CYP3A4", "inhibitor"), ("CYP3A4", "substrate")],
        "half_life_hours": 21.0,
        "protein_binding_pct": 99.8,
        "narrow_therapeutic_index": False,
    },
    # ---- Antivirals ----
    {
        "name": "ritonavir",
        "brand_names": ["Norvir"],
        "drug_class": DrugClass.ANTIVIRAL,
        "mechanism": "HIV protease inhibitor; potent CYP3A4 inhibitor used as pharmacokinetic booster",
        "cyp450": [("CYP3A4", "inhibitor"), ("CYP2D6", "inhibitor"), ("CYP3A4", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Corticosteroids ----
    {
        "name": "prednisone",
        "brand_names": ["Deltasone"],
        "drug_class": DrugClass.CORTICOSTEROID,
        "mechanism": "Synthetic glucocorticoid; prodrug converted to prednisolone",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 3.0,
        "protein_binding_pct": 70.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "dexamethasone",
        "brand_names": ["Decadron"],
        "drug_class": DrugClass.CORTICOSTEROID,
        "mechanism": "Potent synthetic glucocorticoid with minimal mineralocorticoid activity",
        "cyp450": [("CYP3A4", "substrate"), ("CYP3A4", "inducer")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 77.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Respiratory ----
    {
        "name": "albuterol",
        "brand_names": ["ProAir", "Ventolin"],
        "drug_class": DrugClass.BRONCHODILATOR,
        "mechanism": "Short-acting beta-2 adrenergic agonist relaxing bronchial smooth muscle",
        "cyp450": [],
        "half_life_hours": 5.0,
        "protein_binding_pct": 10.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "montelukast",
        "brand_names": ["Singulair"],
        "drug_class": DrugClass.BRONCHODILATOR,
        "mechanism": "Leukotriene receptor antagonist (CysLT1) reducing airway inflammation",
        "cyp450": [("CYP2C8", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 5.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "theophylline",
        "brand_names": ["Theo-Dur"],
        "drug_class": DrugClass.BRONCHODILATOR,
        "mechanism": "Methylxanthine; phosphodiesterase inhibitor and adenosine receptor antagonist",
        "cyp450": [("CYP1A2", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 8.0,
        "protein_binding_pct": 40.0,
        "narrow_therapeutic_index": True,
    },
    # ---- Thyroid ----
    {
        "name": "levothyroxine",
        "brand_names": ["Synthroid", "Levoxyl"],
        "drug_class": DrugClass.THYROID,
        "mechanism": "Synthetic T4 thyroid hormone replacement",
        "cyp450": [],
        "half_life_hours": 168.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": True,
    },
    # ---- Immunosuppressants ----
    {
        "name": "cyclosporine",
        "brand_names": ["Neoral", "Sandimmune"],
        "drug_class": DrugClass.IMMUNOSUPPRESSANT,
        "mechanism": "Calcineurin inhibitor blocking T-cell IL-2 production",
        "cyp450": [("CYP3A4", "substrate"), ("CYP3A4", "inhibitor")],
        "half_life_hours": 8.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "tacrolimus",
        "brand_names": ["Prograf"],
        "drug_class": DrugClass.IMMUNOSUPPRESSANT,
        "mechanism": "Calcineurin inhibitor (FK506); blocks T-cell activation",
        "cyp450": [("CYP3A4", "substrate"), ("CYP3A5", "substrate")],
        "half_life_hours": 12.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "methotrexate",
        "brand_names": ["Trexall"],
        "drug_class": DrugClass.IMMUNOSUPPRESSANT,
        "mechanism": "Dihydrofolate reductase inhibitor; antimetabolite",
        "cyp450": [],
        "half_life_hours": 6.0,
        "protein_binding_pct": 50.0,
        "narrow_therapeutic_index": True,
    },
    # ---- Antihistamines ----
    {
        "name": "diphenhydramine",
        "brand_names": ["Benadryl"],
        "drug_class": DrugClass.ANTIHISTAMINE,
        "mechanism": "First-generation H1 antihistamine; also anticholinergic",
        "cyp450": [("CYP2D6", "substrate")],
        "half_life_hours": 6.0,
        "protein_binding_pct": 80.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "cetirizine",
        "brand_names": ["Zyrtec"],
        "drug_class": DrugClass.ANTIHISTAMINE,
        "mechanism": "Second-generation H1 antihistamine; minimal CNS penetration",
        "cyp450": [],
        "half_life_hours": 8.0,
        "protein_binding_pct": 93.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "loratadine",
        "brand_names": ["Claritin"],
        "drug_class": DrugClass.ANTIHISTAMINE,
        "mechanism": "Second-generation H1 antihistamine; non-sedating",
        "cyp450": [("CYP3A4", "substrate"), ("CYP2D6", "substrate")],
        "half_life_hours": 8.0,
        "protein_binding_pct": 97.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "hydroxyzine",
        "brand_names": ["Vistaril", "Atarax"],
        "drug_class": DrugClass.ANTIHISTAMINE,
        "mechanism": "First-generation H1 antihistamine with anxiolytic properties",
        "cyp450": [("CYP2D6", "substrate")],
        "half_life_hours": 20.0,
        "protein_binding_pct": 93.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Muscle relaxants ----
    {
        "name": "cyclobenzaprine",
        "brand_names": ["Flexeril"],
        "drug_class": DrugClass.MUSCLE_RELAXANT,
        "mechanism": "Centrally acting muscle relaxant structurally related to TCAs",
        "cyp450": [("CYP1A2", "substrate"), ("CYP2D6", "substrate"), ("CYP3A4", "substrate")],
        "half_life_hours": 18.0,
        "protein_binding_pct": 93.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "baclofen",
        "brand_names": ["Lioresal"],
        "drug_class": DrugClass.MUSCLE_RELAXANT,
        "mechanism": "GABA-B receptor agonist reducing spasticity",
        "cyp450": [],
        "half_life_hours": 4.0,
        "protein_binding_pct": 30.0,
        "narrow_therapeutic_index": False,
    },
    # ---- Miscellaneous ----
    {
        "name": "lithium",
        "brand_names": ["Lithobid"],
        "drug_class": DrugClass.OTHER,
        "mechanism": "Mood stabilizer; modulates inositol phosphate, GSK-3 beta, and neuroprotective pathways",
        "cyp450": [],
        "half_life_hours": 24.0,
        "protein_binding_pct": 0.0,
        "narrow_therapeutic_index": True,
    },
    {
        "name": "sildenafil",
        "brand_names": ["Viagra", "Revatio"],
        "drug_class": DrugClass.OTHER,
        "mechanism": "PDE5 inhibitor increasing cGMP-mediated vasodilation",
        "cyp450": [("CYP3A4", "substrate"), ("CYP2C9", "substrate")],
        "half_life_hours": 4.0,
        "protein_binding_pct": 96.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "finasteride",
        "brand_names": ["Proscar", "Propecia"],
        "drug_class": DrugClass.OTHER,
        "mechanism": "5-alpha-reductase inhibitor blocking testosterone to DHT conversion",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 6.0,
        "protein_binding_pct": 90.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "tamsulosin",
        "brand_names": ["Flomax"],
        "drug_class": DrugClass.OTHER,
        "mechanism": "Alpha-1A adrenergic receptor antagonist (uroselective)",
        "cyp450": [("CYP3A4", "substrate"), ("CYP2D6", "substrate")],
        "half_life_hours": 13.0,
        "protein_binding_pct": 99.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "allopurinol",
        "brand_names": ["Zyloprim"],
        "drug_class": DrugClass.OTHER,
        "mechanism": "Xanthine oxidase inhibitor reducing uric acid synthesis",
        "cyp450": [],
        "half_life_hours": 2.0,
        "protein_binding_pct": 0.0,
        "narrow_therapeutic_index": False,
    },
    {
        "name": "colchicine",
        "brand_names": ["Colcrys"],
        "drug_class": DrugClass.OTHER,
        "mechanism": "Tubulin polymerization inhibitor; anti-inflammatory for gout",
        "cyp450": [("CYP3A4", "substrate")],
        "half_life_hours": 30.0,
        "protein_binding_pct": 39.0,
        "narrow_therapeutic_index": True,
    },
]


def _build_cyp_entries(raw: list[tuple[str, str]]) -> list[CYP450Entry]:
    """Convert (enzyme, role) tuples to CYP450Entry models."""
    return [CYP450Entry(enzyme=enz, role=CYP450Role(role)) for enz, role in raw]


def _build_drug(rec: dict) -> Drug:
    """Convert a raw dict record to a Drug model."""
    return Drug(
        name=rec["name"],
        brand_names=rec.get("brand_names", []),
        drug_class=rec["drug_class"],
        mechanism=rec["mechanism"],
        cyp450=_build_cyp_entries(rec.get("cyp450", [])),
        half_life_hours=rec.get("half_life_hours"),
        protein_binding_pct=rec.get("protein_binding_pct"),
        narrow_therapeutic_index=rec.get("narrow_therapeutic_index", False),
    )


class DrugDatabase:
    """In-memory drug database with lookup and search capabilities.

    The database is built from the curated ``_RAW_DRUGS`` list on first
    instantiation. All drug names are stored and matched in lowercase.
    """

    def __init__(self) -> None:
        self._drugs: dict[str, Drug] = {}
        self._brand_index: dict[str, str] = {}
        self._load()

    def _load(self) -> None:
        for rec in _RAW_DRUGS:
            drug = _build_drug(rec)
            self._drugs[drug.name] = drug
            for brand in drug.brand_names:
                self._brand_index[brand.lower()] = drug.name

    @property
    def all_drugs(self) -> list[Drug]:
        """Return all drugs in the database."""
        return list(self._drugs.values())

    @property
    def count(self) -> int:
        return len(self._drugs)

    def lookup(self, name: str) -> Optional[Drug]:
        """Look up a drug by generic name or brand name (case-insensitive)."""
        key = name.strip().lower()
        if key in self._drugs:
            return self._drugs[key]
        generic = self._brand_index.get(key)
        if generic:
            return self._drugs[generic]
        return None

    def lookup_many(self, names: list[str]) -> list[Drug]:
        """Look up multiple drugs, skipping any that are not found."""
        results: list[Drug] = []
        for name in names:
            drug = self.lookup(name)
            if drug is not None:
                results.append(drug)
        return results

    def search(self, query: str) -> list[Drug]:
        """Fuzzy search by substring match on name, brand, class, or mechanism."""
        q = query.strip().lower()
        hits: list[Drug] = []
        for drug in self._drugs.values():
            if (
                q in drug.name
                or q in drug.drug_class.value
                or q in drug.mechanism.lower()
                or any(q in b.lower() for b in drug.brand_names)
            ):
                hits.append(drug)
        return hits

    def by_class(self, drug_class: DrugClass) -> list[Drug]:
        """Return all drugs of a given class."""
        return [d for d in self._drugs.values() if d.drug_class == drug_class]

    def by_cyp_enzyme(self, enzyme: str, role: Optional[CYP450Role] = None) -> list[Drug]:
        """Return drugs that interact with a specific CYP450 enzyme."""
        results: list[Drug] = []
        for drug in self._drugs.values():
            for entry in drug.cyp450:
                if entry.enzyme == enzyme and (role is None or entry.role == role):
                    results.append(drug)
                    break
        return results
